language: cpp

install:
  # Pip cannot install Conan without these upgrades
  - python3 -m pip install --upgrade pip setuptools
  # Install Conan and CMake >= 3.15
  - python3 -m pip install conan cmake

  # Fail if we can't run Conan.
  - conan --version

jobs:
  include:
      #- os: osx
      #compiler: gcc
      #osx_image: xcode12.0    # includes gcc-9 by default
      #env:
      #- GCC_VER="10"
      #- MATRIX_EVAL="CC=gcc-${GCC_VER} && CXX=g++-${GCC_VER}"
      #- os: osx
      #compiler: clang
      #osx_image: xcode12.0
      #env:
      #- MATRIX_EVAL=""
    - os: linux
      dist: focal
      compiler: gcc
      env:
        - GCC_VER="10"
        - MATRIX_EVAL="CC=gcc-${GCC_VER} && CXX=g++-${GCC_VER}"

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            # I couldn't get ${GCC_VER} in here successfully
            - gcc-10
            - g++-10
            - doxygen
            - python3-pip
      after_script:
        - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-${GCC_VER}
    - os: linux
      dist: focal
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang-11 && CXX=clang++-11"
      addons:
         apt:
            packages:
              - doxygen
              - python3-pip
              - clang-11 

before_script:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake -D ENABLE_COVERAGE:BOOL=TRUE ../
  - cmake --build . -- -j2
  - ctest -j2



